# Generated by Django 4.2.7 on 2023-11-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('total_sold', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
            ],
        ),
    ]
