# Generated by Django 4.2.7 on 2023-11-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consumables',
            new_name='Consumable',
        ),
        migrations.AlterModelOptions(
            name='consumable',
            options={'ordering': ['-total_sold']},
        ),
    ]
